version: '3.7'

services:
    rpg-db:
        container_name: rpg-postgres
        image: postgres
        ports:
            - ${DB_PORT}:5432
        restart: always
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
